version: '2'
services:
  nginx.coderdojo:
    image: coderdojoth/web
    container_name: nginx.coderdojo
    hostname: nginx-coderdojo
    volumes:
      - "nginx-log-coderdojo:/var/log/nginx/"
    networks:
      - external-net
    restart: always

networks:
  external-net:
    external:
      name: coderdojo-network

volumes:
  nginx-log-coderdojo:
